<a href="https://colab.research.google.com/github/shinmiura/diveintocode-ml/blob/master/%E8%A1%8C%E5%88%97%E7%A9%8D%E3%81%AE%E5%AE%9F%E8%A3%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

テキストの目的

・数式演算ライブラリのNumPyに慣れる

・行列演算に慣れる

どのように学ぶか

行列積の計算を手計算で行った後、スクラッチ実装することで理解を深めていきます。

以下のような行列A、Bを考えます。


A　=[
      
          [−1, 2, 3], 

          [4, −5, 6], 

          [7, 8, −9]
                      ]


B =[
  
          [0, 2, 1],
          
          [0, 2, −8],

          [2, 9, −1]
                      ]

NumPyで表すと次のようになります。

【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。



A =                       

        [[-1  2  3]

         [ 4 -5  6]

         [ 7  8 -9]]


B = 

        [[ 0  2  1]

         [ 0  2 -8]

         [ 2  9 -1]]


AB =   

        [[(-1×0)+(2×0)+(3×2), (-1×2)+(2×2)+(3×9), (-1×1)+(2×(-8))+(3×(-1))]

         [(4×0)+((-5)×0)+(6×2), (4×2)+((-5)×2)+(6×9), (4×1)+((-5)×(-8))+(6×(-1))]

         [(7×0)+(8×0)+((-9)×2), (7×2)+(8×2)+((-9)×9), (7×1)+(8×(-8))+((-9)×(-1))]] 

    =

        [[  6,  29,  -20]

         [ 12,  52,  38]

         [-18,  -51, -48]]







【問題2】NumPyの関数による計算

この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。


《3種類の違い》


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [ ]:
print(a_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]


In [ ]:
print(b_ndarray)

[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


In [ ]:
# np.matmul()で行列積を求めた場合
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
# @演算子で行列積を求めた場合
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


1.行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる

2.行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる

3.行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる

4.それらの値をすべて足し合わせる

数式で表すと

2
∑
k=0
 
a0
,
k
b
k
,
0


です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。



In [ ]:
# 上記np.matmul()やnp.dot()、@演算子が禁止のためfor文を用いてコードを書く方針を採用
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# リストに計算結果を格納し、後ほど処理する
result = []

for i in range(3):
  for j in range(3):
    for k in range(3):
      result.append(a_ndarray[i, k] * b_ndarray[k, j])
      print("a:{}, b:{}, result = {}".format(a_ndarray[i, k], b_ndarray[k, j], result))

a:-1, b:0, result = [0]
a:2, b:0, result = [0, 0]
a:3, b:2, result = [0, 0, 6]
a:-1, b:2, result = [0, 0, 6, -2]
a:2, b:2, result = [0, 0, 6, -2, 4]
a:3, b:9, result = [0, 0, 6, -2, 4, 27]
a:-1, b:1, result = [0, 0, 6, -2, 4, 27, -1]
a:2, b:-8, result = [0, 0, 6, -2, 4, 27, -1, -16]
a:3, b:-1, result = [0, 0, 6, -2, 4, 27, -1, -16, -3]
a:4, b:0, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0]
a:-5, b:0, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0]
a:6, b:2, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12]
a:4, b:2, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8]
a:-5, b:2, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10]
a:6, b:9, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10, 54]
a:4, b:1, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10, 54, 4]
a:-5, b:-8, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10, 54, 4, 40]
a:6, b:-1, result = [0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10, 54, 4, 40, -6]
a:7, b:0, result = [0

In [ ]:
print(result)

[0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10, 54, 4, 40, -6, 0, 0, -18, 14, 16, -81, 7, -64, 9]


In [ ]:
# 行ごとに集計したいため、３列ごとを１行としてreshapeする
c_ndarray = np.array(result)
d_ndarray = c_ndarray.reshape(9, 3)

In [ ]:
# 各行を集計して3×3の行列にすれば解答となる
a = np.sum(d_ndarray, axis=1)
answer3 = a.reshape(3,3)
answer3

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題４】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。


c
i
,
j
=
2
∑
k
=
0
 
a
i
,
k
b
k
,
j

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。



In [ ]:
def matrix_product(a_ndarray, b_ndarray):
  """
  行列Aと行列Bをインプットすると行列積ABを返す関数
　　　　Parameters
  -----------
  a_ndarray : ndarray型
  　　　　行列A
  b_ndarray : ndarray型
  　　　　行列B

  Returns
  -----------
  result : ndarray型
  　　　　行列積AB
  """
  # リストに計算結果を格納し、後ほど処理する
  result = []
  
  for i in range(3):
    for j in range(3):
      for k in range(3):
        result.append(a_ndarray[i, k] * b_ndarray[k, j])

  return result

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(matrix_product(a_ndarray, b_ndarray))

c_ndarray = np.array(result)
d_ndarray = c_ndarray.reshape(9, 3)

a = np.sum(d_ndarray, axis=1)
answer4 = a.reshape(3,3)
answer4

[0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10, 54, 4, 40, -6, 0, 0, -18, 14, 16, -81, 7, -64, 9]


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題５】計算が定義されない入力を判定する


問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [43]:
def matrix_product(d_ndarray, e_ndarray):
  """
  行列Dと行列Eをインプットすると行列積DEを返す関数
　　　　Parameters
  -----------
  d_ndarray : ndarray型
  　　　　行列D
  e_ndarray : ndarray型
  　　　　行列E

  Returns
  -----------
  result : ndarray型
  　　　　行列積DE
  """
  # リストに計算結果を格納し、後ほど処理する
  result = []
  
  for i in range(3):
    for j in range(3):
      for k in range(3):
        result.append(a_ndarray[i, k] * b_ndarray[k, j])

  return result

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(matrix_product(d_ndarray, e_ndarray))

f_ndarray = np.array(result)
g_ndarray = f_ndarray.reshape(9, 3)

b = np.sum(g_ndarray, axis=1)
answer5 = b.reshape(3,3)
answer5

[0, 0, 6, -2, 4, 27, -1, -16, -3, 0, 0, 12, 8, -10, 54, 4, 40, -6, 0, 0, -18, 14, 16, -81, 7, -64, 9]


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題６】転置

片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [ ]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [ ]:
# 行列Bを転置
bT_ndarray = b_ndarray.T
bT_ndarray

array([[ 0,  0,  2],
       [ 2,  2,  9],
       [ 1, -8, -1]])

In [ ]:
a_ndarray * bT_ndarray

array([[  0,   0,   6],
       [  8, -10,  54],
       [  7, -64,   9]])